import React from 'react';
import { Link } from 'gatsby';
import Image from 'gatsby-image';
// Page generated by gatsby-node.js
const Project = ({ title, shortDescription, description, url, imageData }) => {
  return (
  <div className='project'>
    <h1>{ title }</h1>
    <Image fluid={ imageData } alt={ title } />
    <p>{ description }</p>
    <p>
      <a href={ url } target='_blank' rel='noopener noreferrer'>View this project online &rarr;</a>
    </p>
    <p>
      <Link to='/'>&larr; Home</Link>
    </p>
  </div>
  );
};

export default Project; 


